version: '3.8'

services:
  # MySQL 数据库（核心修改：移除宿主机端口映射，避免占用3306）
  mysql:
    image: mysql:8.0
    container_name: noval-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Aa!+1234}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-novel_db}
      TZ: Asia/Shanghai
    # 关键：删除 ports 配置，不暴露宿主机3306端口，仅容器内可用
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init_reader_tables.py:/docker-entrypoint-initdb.d/init.py:ro
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - noval-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-Aa!+1234}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存（已移除宿主机端口，保持不变）
  redis:
    image: redis:7-alpine
    container_name: noval-redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - noval-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # 后端应用（保持不变，内部通过容器名+3306连接MySQL）
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noval-backend
    restart: always
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    environment:
      # 数据库配置：仍用3306端口，通过容器名"mysql"通信（无需改代码）
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "Aa!+1234"
      DB_NAME: novel_db
      # Redis配置（不变）
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Flask配置
      FLASK_ENV: ${FLASK_ENV:-production}
      PYTHONUNBUFFERED: 1
      TZ: Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./configs:/app/configs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - noval-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx 前端服务器（保持不变）
  nginx:
    image: nginx:alpine
    container_name: noval-nginx
    restart: always
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - noval-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  noval-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local